modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "assetbridge"
version = "${version}"
displayName = "Asset Bridge "
authors = "Pitan"
description = '''
A Minecraft mod that loads assets such as blocks from other mods, allowing them to be used visually without their original functionality.
'''
#logoFile = ""

[[dependencies.assetbridge]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.assetbridge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2]"
ordering = "NONE"
side = "BOTH"

