# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# Mod properties
mod_version=0.0.5
maven_group=net.pitan76
archives_name=assetbridge
enabled_platforms=fabric,forge
# Minecraft properties
minecraft_version=1.18.2
# Dependencies
fabric_loader_version=0.19.3
fabric_api_version=0.77.0+1.18.2
forge_version=1.18.2-40.3.12
